# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - synonyms-client

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bb0f49a0ad144ce7a0d99272de4960d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2df9ca1fe24646b5ad5c0aea06c3b2e3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bb0f49a0ad144ce7a0d99272de4960d0 }}/synonyms-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'synonyms-client'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_523341de2b5442f69f383fc878946f36 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bb0f49a0ad144ce7a0d99272de4960d0 }}/synonyms-client:${{ github.sha }}'